university_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DW_HOST', 'localhost') }}"
      port: "{{ env_var('DW_PORT', '5432') | int }}"
      user: "{{ env_var('DW_USER', 'datawarehouse') }}"
      password: "{{ env_var('DW_PASSWORD', 'datawarehouse') }}"
      dbname: "{{ env_var('DW_DATABASE', 'university_dw') }}"
      schema: gold
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: postgres
      host: "{{ env_var('DW_HOST') }}"
      port: "{{ env_var('DW_PORT') | int }}"
      user: "{{ env_var('DW_USER') }}"
      password: "{{ env_var('DW_PASSWORD') }}"
      dbname: "{{ env_var('DW_DATABASE') }}"
      schema: gold
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
